feat: add finding for super class in MethodResolver and FieldResolver
InventivetalentDev/ReflectionHelper pull request #62
Opened 2024-04-16 16:48 UTC by lulu2002

2024-04-22 10:34 UTC, InventivetalentDev requested changes
thanks!

2024-04-22 10:34 UTC, InventivetalentDev commented on src/main/java/org/inventivetalent/reflection/resolver/FieldResolver.java
> +                System.out.println("superclass: " + superclass.getName());
```suggestion
```

2024-04-22 10:34 UTC, InventivetalentDev commented on src/main/java/org/inventivetalent/reflection/resolver/ResolverAbstract.java
> +				e.printStackTrace();
wrap in AccessUtil.VERBOSE check

2024-04-22 10:34 UTC, InventivetalentDev commented on src/test/java/org/inventivetalent/reflectionhelper/test/ResolverTest.java
> +    }
probably add another test to make sure it still prioritizes fields in the initial class (e.g. if there's also a `b` field in BaseClass, it should still resolve the "sub" field from SubClass)

2024-04-22 13:38 UTC, lulu2002 commented
Hello, thanks for reviewing! I've changed all of that and for test part I've rename test methods with `should` prefix, please check it out!

2024-05-03 19:44 UTC, InventivetalentDev approved these changes

2024-05-03 19:44 UTC, merged